import { test, expect } from '@playwright/test';
import { Page } from '@playwright/test';

test('test @lambdatest', async ({ page }: { page: Page }) => {
  await page.goto('https://ecommerce-playground.lambdatest.io/');
  await page.getByRole('textbox', { name: 'Search For Products' }).click();
  await page.getByRole('textbox', { name: 'Search For Products' }).fill('HP');
  await page.getByRole('link', { name: 'HP LP3065' }).nth(1).click();
  await page.getByRole('button', { name: 'Add to Cart' }).click();
  await page.getByRole('link', { name: 'View Cart ' }).click();
  await page.getByRole('link', { name: 'Checkout' }).click();
  await page.getByText('Guest Checkout').click();
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).click();
  await page.getByRole('textbox', { name: 'First Name*' }).fill('Rakesh');
  await page.getByRole('textbox', { name: 'Last Name*' }).click();
  await page.getByRole('textbox', { name: 'Last Name*' }).fill('Kumar');
  await page.getByRole('textbox', { name: 'E-Mail*' }).click();
  await page.getByRole('textbox', { name: 'E-Mail*' }).fill('test@gmail.com');
  await page.getByRole('textbox', { name: 'Telephone*' }).click();
  await page.getByRole('textbox', { name: 'Telephone*' }).fill('9728938935');
  await page.getByRole('textbox', { name: 'Address 1*' }).click();
  await page.getByRole('textbox', { name: 'Address 1*' }).fill('2030 Mac Drive');
  await page.getByRole('textbox', { name: 'City*' }).click();
  await page.getByRole('textbox', { name: 'City*' }).fill('Cleveland');
  await page.getByRole('textbox', { name: 'Post Code*' }).click();
  await page.getByRole('textbox', { name: 'Post Code*' }).fill('44026');
  await page.locator('#input-payment-country').selectOption('223');
  await page.locator('#input-payment-zone').selectOption('3659');
  await page.getByText('I have read and agree to the Terms & Conditions').click();
  await page.getByRole('button', { name: 'Continue ' }).click();
  await page.getByRole('button', { name: 'Confirm Order ' }).click();
  await expect(page.locator('#content')).toContainText('Your order has been successfully processed!');
  await page.getByRole('link', { name: 'Continue' }).click();
});