export const TEST_EMAIL = 'test@gmail.com';

export const CHECKOUT_FIRST_NAME = 'Test';
export const CHECKOUT_LAST_NAME = 'User';
export const CHECKOUT_PHONE = '1234567890';
export const CHECKOUT_ADDRESS = '123 Straight Street';
export const CHECKOUT_CITY = 'Dallas';
export const CHECKOUT_STATE = 'Texas';
export const CHECKOUT_POST_CODE = '75001';

export const CHECKOUT_GUEST_FIRST_NAME = 'testfirst';
export const CHECKOUT_GUEST_LAST_NAME = 'testlast';

export const CHECKOUT_ELECTRONICS_PHONE = '9098726735';
export const CHECKOUT_ELECTRONICS_ADDRESS = '1234 test street';
export const CHECKOUT_ELECTRONICS_STATE = 'Michigan';
export const CHECKOUT_ELECTRONICS_CITY = 'Troy';
export const CHECKOUT_ELECTRONICS_POST_CODE = '78234';

export const CHECKOUT_KIDS_FIRST_NAME = 'Testname';
export const CHECKOUT_KIDS_LAST_NAME = 'Testlastname';
export const CHECKOUT_KIDS_PHONE = '9726635421';
export const CHECKOUT_KIDS_ADDRESS = '2890 Spring Drive';
export const CHECKOUT_KIDS_CITY = 'Troy';
export const CHECKOUT_KIDS_STATE = 'MI';
export const CHECKOUT_KIDS_POST_CODE = '89283';

export default {
  TEST_EMAIL,
  CHECKOUT_FIRST_NAME,
  CHECKOUT_LAST_NAME,
  CHECKOUT_PHONE,
  CHECKOUT_ADDRESS,
  CHECKOUT_CITY,
  CHECKOUT_STATE,
  CHECKOUT_POST_CODE,
  CHECKOUT_GUEST_FIRST_NAME,
  CHECKOUT_GUEST_LAST_NAME,
  CHECKOUT_ELECTRONICS_PHONE,
  CHECKOUT_ELECTRONICS_ADDRESS,
  CHECKOUT_ELECTRONICS_STATE,
  CHECKOUT_ELECTRONICS_CITY,
  CHECKOUT_ELECTRONICS_POST_CODE,
  CHECKOUT_KIDS_FIRST_NAME,
  CHECKOUT_KIDS_LAST_NAME,
  CHECKOUT_KIDS_PHONE,
  CHECKOUT_KIDS_ADDRESS,
  CHECKOUT_KIDS_CITY,
  CHECKOUT_KIDS_STATE,
  CHECKOUT_KIDS_POST_CODE,
};
